---

- name: install nginx
  block:
    - name: update nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: nginx
      notify:
        - reload nginx
      become: yes

    - name: update nginx statics
      copy:
        src: "files/"
        dest: "{{ root_dir }}"
        owner: nginx
      notify:
        - reload nginx
      become: yes

    - name: off firewalld
      service:
        name: firewalld.service
        state: stopped
        daemon_reload: no
        enabled: no
      become: yes
