---

- name: install nginx
  block:
    - name: prepare steps for nginx
      block:
        - name: Install EPEL repo
          yum:
            name: epel-release
            state: present
          become: yes

    - name: install nginx server
      yum:
        name: nginx
        state: present
        update_cache: yes
      become: yes