apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redmine
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate  
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:4.1.1
        imagePullPolicy: "IfNotPresent"
        env:
          - name: REDMINE_DB_POSTGRES
            value: database
          - name: REDMINE_DB_USERNAME
            value: testuser
          - name: REDMINE_DB_DATABASE
            value: testdatabase
          - name: REDMINE_DB_PASSWORD
            value: testpassword
#            valueFrom:
#              secretKeyRef:
#                name: sec-pg1-rm1
#                key: REDMINE_DB_PASSWORD
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: sec-rm1
                key: REDMINE_SECRET_KEY_BASE         
        ports:
        - containerPort: 3000
