---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pg1
  labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local