env1 = int(input("Веедите число 1 >>>"))
env_str1 = input("Введите 1-ое слово или предложение>>>")
env2 = int(input("Введите число 2 >>>"))
env_str2 = input("Введите 2-ое слово или предложение>>>")
print(f"Вы ввели  {env1} {env_str1} {env2} {env_str2}")
