- hosts: webservers
  tasks: 
    - name: off firewalld
      service:
        name: firewalld.service
        state: stopped
        daemon_reload: no
        enabled: no
      become: yes
      tags: docker