apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate  
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.13
        imagePullPolicy: "IfNotPresent"
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata  
          - name: POSTGRES_DB
            value: testdatabase
          - name: POSTGRES_USER
            value: testuser
          - name: POSTGRES_PASSWORD
#          value: adminS3cret
            valueFrom:
              secretKeyRef:
                name: sec-pg1
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
          - name: pv-pg1
            mountPath: /var/lib/pgsql/data
      volumes:      
        - name: pv-pg1
          persistentVolumeClaim:
            claimName: pvc-pg1