apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pg1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/memfis/kub_work/pg1
  storageClassName: local  