apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvprometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/kzuykov/kuber_less/storage_prometheus
  storageClassName: local 